spring.application.name=auth

# Render automatically provides PORT
server.port=${PORT:8081}

# ===============================
# Database (ENV based)
# ===============================
spring.datasource.url=${DATABASE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# ===============================
# JWT Configuration (ENV based)
# ===============================
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
